console.log("A：DATA完成了人员管理；")
console.log("B：STUDENT完成了资源管理；")
console.log("C：TEACHER完成了统计分析；")
console.log("D：DOCTER可以开始对功能模块赋权限了；")
console.log("E：SOMEONE的权限已经做完了！项目完成了")
console.log("k：这里测试")
console.log("L：什么")